language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git-core

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
    - cd /tmp/wordpress/
    - git init .
    - cd /home/travis/build/ExpandedFronts/Revisr/
    - git config user.name "revisr"
    - git config user.email "support@expandedfronts.com"

script: phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover